### ISSUE TITLE
Error: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by 27cm** [dkhamsing/awesome_bot#103]
Travis CI output for this [README.md](https://github.com/27cm/awesome-zendframework/blob/master/README.md) file:
```bash
$ awesome_bot README.md --white-list travis-ci,stackoverflow
...
No issues :-)
/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/json/common.rb:285:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/json/common.rb:285:in `generate'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/json/common.rb:285:in `pretty_generate'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/result.rb:79:in `block in write'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/result.rb:79:in `open'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/result.rb:79:in `write'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/write.rb:61:in `write_results'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/cli.rb:134:in `cli_process'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/cli.rb:46:in `block in cli'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/cli.rb:45:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/lib/awesome_bot/cli.rb:45:in `cli'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.13.4/bin/awesome_bot:6:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/awesome_bot:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/awesome_bot:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dkhamsing** [comment]
Thanks for the report
Will take a look

**Comment by dkhamsing** [comment]
@27cm pushed out version `1.13.5` with the fix

**Comment by 27cm** [comment]
:+1:  Thanks so much @dkhamsing
