### ISSUE TITLE
Awesome_bot hanging

### ISSUE THREAD

**Issue by jdorfman** [dkhamsing/awesome_bot#131]
Running it on this branch: https://github.com/jdorfman/awesome-json-datasets/tree/still-awesome-p3

```
> awesome_bot README-etc.md --allow-timeout -t 1
> Checking links in README-etc.md
> Will allow network timeouts
> Connection timeout = 1s
Links to check: 304, 299 unique
...
  298. https://www.nasa.gov/digitalstrategy/costsavings.json 
  299. https://www.nasa.gov/digitalstrategy/bureaudirectory.json 
Checking URLs: ✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?x✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓→✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓→→✓→→→✓✓✓✓✓✓✓✓✓✓✓✓x✓✓✓✓✓✓✓✓✓✓→→→→→→→→→→→→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓x✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓x✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓
```

Killed process (30+ minutes in):

```
^C?/usr/local/lib/ruby/gems/2.4.0/gems/parallel-1.11.1/lib/parallel.rb:207:in `value': Interrupt
        from /usr/local/lib/ruby/gems/2.4.0/gems/parallel-1.11.1/lib/parallel.rb:207:in `map!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/parallel-1.11.1/lib/parallel.rb:207:in `in_threads'
        from /usr/local/lib/ruby/gems/2.4.0/gems/parallel-1.11.1/lib/parallel.rb:335:in `work_in_threads'
        from /usr/local/lib/ruby/gems/2.4.0/gems/parallel-1.11.1/lib/parallel.rb:262:in `map'
        from /usr/local/lib/ruby/gems/2.4.0/gems/parallel-1.11.1/lib/parallel.rb:217:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/awesome_bot-1.15.0/lib/awesome_bot/net.rb:50:in `statuses'
        from /usr/local/lib/ruby/gems/2.4.0/gems/awesome_bot-1.15.0/lib/awesome_bot/check.rb:45:in `check'
        from /usr/local/lib/ruby/gems/2.4.0/gems/awesome_bot-1.15.0/lib/awesome_bot/cli.rb:120:in `cli_process'
        from /usr/local/lib/ruby/gems/2.4.0/gems/awesome_bot-1.15.0/lib/awesome_bot/cli.rb:48:in `block in cli'
        from /usr/local/lib/ruby/gems/2.4.0/gems/awesome_bot-1.15.0/lib/awesome_bot/cli.rb:47:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/awesome_bot-1.15.0/lib/awesome_bot/cli.rb:47:in `cli'
        from /usr/local/lib/ruby/gems/2.4.0/gems/awesome_bot-1.15.0/bin/awesome_bot:6:in `<top (required)>'
        from /usr/local/bin/awesome_bot:22:in `load'
        from /usr/local/bin/awesome_bot:22:in `<main>'
```

via Debug info: https://github.com/jdorfman/awesome-json-datasets/issues/179#issuecomment-298379875

**Comment by dkhamsing** [comment]
will take a look, thx

**Comment by dkhamsing** [comment]
hm runs fine locally
how did u run this
what version

here are my results

```
...
  299. https://creativecommons.org/publicdomain/zero/1.0/ 
  300. https://www.maxcdn.com 
Checking URLs: ✓✓✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓x✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓??????✓??✓???✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓???✓✓✓✓✓✓✓✓✓?✓????✓?✓?✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓??✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓

Issues :-(
> Links 
  01. [L008] 302 https://www.stickermule.com/marketplace/embed_img/10034  → https://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/10034/large/1453026750/awesome.png 
  02. [L054] 404 https://api.bitcoinaverage.com/ticker/global/ENTER-SYMBOL/  
  03. [L095]  https://data.cityofchicago.org/api/views/ijzp-q8t2/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  04. [L122] 301 http://pokeapi.co/api/v2/ability/1  → http://pokeapi.co/api/v2/ability/1/ 
  05. [L124] 301 http://magic.wizards.com  → http://magic.wizards.com/en 
  06. [L146]  https://chronicdata.cdc.gov/api/views/g4ie-h725/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  07. [L148]  https://data.medicare.gov/api/views/77hc-ibv8/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  08. [L150]  https://chhs.data.ca.gov/api/views/7kri-yb7t/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  09. [L151]  https://data.ny.gov/browse?limitTo=datasets&utf8=%E2%9C%93 Connection reset by peer - SSL_connect 
  10. [L152]  https://data.ny.gov/api/views/kwxv-fwze/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  11. [L153]  https://data.ny.gov/api/views/9a8c-vfzj/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  12. [L154]  https://data.ny.gov/api/views/cb42-qumz/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  13. [L155]  https://data.ny.gov/api/views/6nvr-tbv8/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  14. [L156]  https://data.ny.gov/api/views/pxa9-czw8/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  15. [L157]  https://data.ny.gov/api/views/5xaw-6ayf/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  16. [L158]  https://data.ny.gov/api/views/d6yy-54nr/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  17. [L159]  https://data.cityofnewyork.us/api/views/5b3a-rs48/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  18. [L171] 301 http://www.justice.gov/api/v1/vacancy_announcements.json?pagesize=2  → https://www.justice.gov/api/v1/vacancy_announcements.json?pagesize=2 
  19. [L193]  https://data.gov.in/node/1084041/datastore/export/json Connection reset by peer - SSL_connect 
  20. [L194]  https://data.gov.in/node/739941/datastore/export/json Connection reset by peer - SSL_connect 
  21. [L195]  https://data.gov.in/node/135611/datastore/export/json Connection reset by peer - SSL_connect 
  22. [L196]  https://data.gov.in/node/100853/datastore/export/json Connection reset by peer - SSL_connect 
  23. [L210]  https://data.michigan.gov/browse Connection reset by peer - SSL_connect 
  24. [L211]  https://data.michigan.gov/api/views/p54v-8v6s/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  25. [L212]  https://data.michigan.gov/api/views/bcct-6rxt/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  26. [L213]  https://data.michigan.gov/api/views/7rph-su5f/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  27. [L214]  https://data.michigan.gov/api/views/he9h-7fpa/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  28. [L215]  https://data.michigan.gov/api/views/pxdv-rgvb/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  29. [L216]  https://data.michigan.gov/api/views/nndy-b6rm/rows.json?accessType=DOWNLOAD Connection reset by peer - SSL_connect 
  30. [L263]  https://data.nasa.gov/resource/y77d-th95.json SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure 
  31. [L264]  https://data.nasa.gov/resource/2vr3-k9wn.json SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure 
> Dupes 
  1. [L001] https://github.com/sindresorhus/awesome
  2. [L125] https://mtgjson.com
  3. [L181] http://parliamentdata.ca/
```

**Comment by dkhamsing** [comment]
btw, u can also use option `--allow-ssl`

```
...
  300. https://www.maxcdn.com 
Checking URLs: ✓✓✓✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓x✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓?✓✓✓?✓????✓??????→✓✓✓✓→✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓???✓?✓✓✓✓✓✓✓?✓✓??????✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓??✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓

Issues :-(
> Links 
  1. [L008] 302 https://www.stickermule.com/marketplace/embed_img/10034  → https://d21ii91i3y6o6h.cloudfront.net/gallery_images/from_proof/10034/large/1453026750/awesome.png 
  2. [L054] 404 https://api.bitcoinaverage.com/ticker/global/ENTER-SYMBOL/  
  3. [L122] 301 http://pokeapi.co/api/v2/ability/1  → http://pokeapi.co/api/v2/ability/1/ 
  4. [L124] 301 http://magic.wizards.com  → http://magic.wizards.com/en 
  5. [L171] 301 http://www.justice.gov/api/v1/vacancy_announcements.json?pagesize=2  → https://www.justice.gov/api/v1/vacancy_announcements.json?pagesize=2 
> Dupes 
  1. [L001] https://github.com/sindresorhus/awesome
  2. [L125] https://mtgjson.com
  3. [L181] http://parliamentdata.ca/
```

**Comment by jdorfman** [comment]
@dkhamsing same thing.

Env:
* MacOS
* Ruby `2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`
* `awesome_bot-1.15.0`

What else do you need to debug?

**Comment by jdorfman** [comment]
FWIW it worked perfectly fine the day before.

**Comment by dkhamsing** [comment]
Hm did your machine get updated??

**Comment by jdorfman** [comment]
Nope. So weird.

**Comment by dkhamsing** [comment]
🤔

**Comment by dkhamsing** [comment]
@jdorfman hey must be the ruby version

anyway you can change it to `ruby 2.0.0..`

**Comment by dkhamsing** [comment]
not super familiar with it but i hear good things about https://github.com/rbenv/rbenv

**Comment by jdorfman** [comment]
Out of curiosity why only support a version of Ruby from `2015`?

**Comment by dkhamsing** [comment]
2015 is when the project started, yours is the first report of an issue 😅

**Comment by dkhamsing** [comment]
I think 2.2 should work

**Comment by dkhamsing** [comment]
2.2 is the ruby available on travis https://docs.travis-ci.com/user/languages/ruby/ which is a typical use for this tool

**Comment by jdorfman** [comment]
@dkhamsing ok I'll close this for now. Thanks for the help.
