### ISSUE TITLE
Unknown reason for "Incompatible character encodings"

### ISSUE THREAD

**Issue by hoppfrosch** [dkhamsing/awesome_bot#82]
Running awesome-bot on our awesome-list after adding a new entry, awesome-bot exits with an error. Don't have any idea where the error comes from - as my new entry looks correct (no special characters used) and the previous travis run was successful.

The entry the error occurs on, is an old entry which previpusly passed awesome-bot related test without any error.

Any idea?

https://github.com/ahkscript/awesome-AutoHotkey/pull/99

```
 040. [L130] 200 https://autohotkey.com/board/topic/53827-ahksock-a-simple-ahk-implementation-of-winsock-tcpip/  
/usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/output.rb:63:in `output_redirect': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/output.rb:58:in `output'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/cli.rb:103:in `block in cli_process'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/cli.rb:102:in `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/cli.rb:102:in `each_with_index'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/cli.rb:102:in `cli_process'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/cli.rb:45:in `block in cli'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/cli.rb:44:in `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/lib/awesome_bot/cli.rb:44:in `cli'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/awesome_bot-1.9.0/bin/awesome_bot:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/awesome_bot:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/awesome_bot:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dkhamsing** [comment]
Will take a look, thx

**Comment by dkhamsing** [comment]
@hoppfrosch think I found the error.. the redirect for https://autohotkey.com/board/topic/94376- has some special encoding that the script is not handling

```ruby
 "location"=>"//autohotkey.com/board/topic/94376-socket-class-\xC3\xBCberarbeitet/"
```

will try to fix asap!

**Comment by dkhamsing** [comment]
@hoppfrosch should be fixed in version `1.9.1`
thx

**Comment by dkhamsing** [comment]
can u try rerunning this

**Comment by hoppfrosch** [comment]
Everything works now again - thx for the rapid fix
