### ISSUE TITLE
Encode error

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/awesome_bot#93]
https://circleci.com/gh/dkhamsing/scan-urls/67
```
encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/json/common.rb:285:in `generate'`
```

**Comment by sotayamashita** [comment]
Is it same error: 

```
  2. [L111]  http://www.starbucks.com/ Net::ReadTimeout 
/home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/json/common.rb:285:in `encode': "\xE2" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/json/common.rb:285:in `generate'
	from /home/travis/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/json/common.rb:285:in `pretty_generate'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/result.rb:79:in `block in write'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/result.rb:79:in `open'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/result.rb:79:in `write'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/cli.rb:176:in `cli_write_results'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/cli.rb:168:in `cli_process'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/cli.rb:47:in `block in cli'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/cli.rb:46:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/lib/awesome_bot/cli.rb:46:in `cli'
	from /home/travis/.rvm/gems/ruby-2.2.0/gems/awesome_bot-1.12.1/bin/awesome_bot:6:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/awesome_bot:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/awesome_bot:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sotayamashita** [comment]
```diff
- content = untrusted.encode('UTF-16', :invalid => :replace, :replace => '').encode('UTF-8')
+ content = untrusted.encode('UTF-16', :invalid => :replace, :undef => :replace => '').encode('UTF-8')
```

* http://ruby-doc.org/core-2.2.0/String.html#method-i-encode

**Comment by dkhamsing** [comment]
Thx, will try

**Comment by dkhamsing** [comment]
Hm cannot reproduce this 😕 
Closing for now
